### PR TITLE
Add Bonfirestellar anchor

### PR DESCRIPTION
**Pull request by krishankripal**
Commit id: f8f1da7c47139a8d4c6bd6289d38d2c9d2c62f5519f9b9a97ba2331f4c…

…e2b416

### CODE REVIEW

**Comment by krishankripal** [comment]
Request for PR approval
@shiny-mountain @flat-resonance @little-wave @dmgmyza @v-urbanovich

**Comment by divsinghal** [comment]
Hi @shiny-mountain @flat-resonance @little-wave @dmgmyza @v-urbanovich ,

Could you please review the PR once?

**Review by divsinghal — APPROVED** [review]

**Comment by divsinghal** [comment]
Hi @shiny-mountain @flat-resonance @little-wave @dmgmyza @v-urbanovich ,

Could you please merge the PR if you are happy with the changes?

**Comment by Feltmarket** [comment]
Hello @shiny-mountain @flat-resonance @little-wave @dmgmyza @v-urbanovich @divsinghal Bonfirestellar Community appreciates everyones hard work. Is everything needed for a successful merge?

**Comment by divsinghal** [comment]
Hi @shiny-mountain @flat-resonance @little-wave @dmgmyza @v-urbanovich ,

Could you please merge the PR if you are happy with the changes?

**Comment by divsinghal** [comment]
Hi @shiny-mountain @flat-resonance @little-wave @dmgmyza @v-urbanovich ,

Could you please merge the PR if you are happy with the changes?

**Review by Feltmarket — APPROVED** [review]

**Pull request closed without merging**
